### ISSUE TITLE
Strange "Out of memory" compiler error

### ISSUE THREAD

**Issue by SergejKern** [jrsoftware/issrc#158] opened 2015-04-29 09:52 UTC
Dear contributors,

I (and my colleagues) get strange compiler error "Out of memory".

First of all - do I have enough memory on my machine? Yes, I ~~can~~ have.

I use Win7 x64 with 4 GB RAM and 5.5.5(u), but this problem occurred with 5.5.2(u) also. I tried to watch numbers in task manager in Physical Memory (MB) section - and I get no clue. Even if Physicyl Memory (MB) / Free shows 0 (zero), IS compiler normally compiles without errors. But sometimes....

If this error occurs, it **always** occurs after compressing second file from file section - no matter which.
How I do resolve this error:
* Close IS compiler and start it again (success rate 50/50)
* Just wait (success rate 50/50)
* Close other programs (but there are not so many to close) (success rate also 50/50)
* Reboot windows (works nearly always)

Most of the time this error does not occur.

There is one possibility to get IS compiler to produce this error: 
1. Successfully compile and start debugging
2. Click on Run/Terminate
3. Try to recompile

Sometimes this strange error does occur after that, more likely it does not.

Size of our code is 1,3 MB in several files. Size of files differs from dev machine to dev machine - is about 6GB, most of the files are marked as externals.

There is no difference in output for "Compiling [Code] section" if I set verboselevel to 9 or to 1.

Last output is:
```
Compiling [Code] section
Creating setup files
   Compressing Setup program executable
   Compressing: C:\[..]\resources\settings.xml
   Compressing: C:\[..]\resources\countries\bg.countries.txt
*** Compile aborted.
```

Maybe you could introduce more verbose messages so that it is possible to understand why this error occurs.

Best regards,
Sergej

**Comment by DeeHants** [comment] 2015-04-29 10:05
Can you post your entire `[Setup]` section?
How big is `bg.countries.txt`?

**Comment by SergejKern** [comment] 2015-04-29 13:57
bg.countries.txt is 3KB big

```
[Setup]
AppID={#SomeDefinedGUID}
AppName={#MyAppName}
AppVersion={#SomeDefinedID}
AppVerName={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AppContact=email@domain.com
AppCopyright=Company name
LicenseFile=resources/empty_license.txt
DefaultDirName={#MyDefaultDirName}
DefaultGroupName={#MyDefaultGroupName}
OutputDir={#OutputPath}
OutputBaseFilename={#MyOutputBaseFilename}
PrivilegesRequired=admin
AlwaysShowDirOnReadyPage=true
AlwaysShowGroupOnReadyPage=true
SetupLogging=true
AllowCancelDuringInstall=false
ShowComponentSizes=false
MinVersion=0,5.01.2600
AllowUNCPath=false
DisableStartupPrompt=true
UsePreviousTasks=false
DiskSpanning=true
DiskClusterSize=2048
DiskSliceSize=544913782
SlicesPerDisk=13
Compression={#MyCompression}
SolidCompression=false
VersionInfoVersion={#MyAppVersion}
VersionInfoCompany=Company name
VersionInfoCopyright=Company name
VersionInfoDescription=App name Setup
VersionInfoProductName=App name
UninstallDisplayName={#MyAppName}
UninstallDisplayIcon={#AppDirEsitronic}\{#MyAppExeName}
DisableProgramGroupPage=yes
AlwaysRestart=no
RestartIfNeededByRun=false
WizardImageFile=.\resources\icons\TitelImage.bmp
WizardSmallImageFile=.\resources\icons\TitelImageSmall.bmp
UninstallLogMode=new
```

**Comment by martijnlaan** [comment] 2016-02-23 14:05
Closing this. Can't reproduce and your listing above doesn't show what kind of compression you use. Perhaps you need to set ``LZMAUseSeparateProcess`` to ``yes``.

**Closed by martijnlaan** 2016-02-23 14:05 UTC
Labels: compiler
